# Generated by Django 3.2.11 on 2022-01-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(choices=[('QT', 'text'), ('QI', 'image')], default='QT', max_length=2)),
                ('answerType', models.CharField(choices=[('AT', 'text'), ('AS', 'select')], default='AT', max_length=2)),
            ],
        ),
    ]
