# Generated by Django 3.2.11 on 2022-01-29 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.BigAutoField(help_text='Game ID', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='QnaSet',
            fields=[
                ('id', models.BigAutoField(help_text='qnaSet ID', primary_key=True, serialize=False)),
                ('QText', models.TextField(blank=True, null=True)),
                ('Qimage', models.ImageField(blank=True, null=True, upload_to='question/%Y/%m/%d')),
                ('answer', models.TextField(blank=True)),
                ('game_id', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='game', to='main.game')),
            ],
        ),
    ]
