# Generated by Django 3.2.11 on 2022-01-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220130_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnaset',
            name='answerList1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='qnaset',
            name='answerList2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='qnaset',
            name='answerList3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='qnaset',
            name='answerList4',
            field=models.TextField(blank=True, default=''),
        ),
    ]
